# Generated by Django 5.2 on 2026-03-13 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Category-specific attributes (e.g., RAM, storage, size, material).'),
        ),
    ]
