# Generated by Django 5.2 on 2026-07-10 21:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_reserved_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='height_cm',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='product',
            name='length_cm',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_class',
            field=models.CharField(default='STANDARD', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_category',
            field=models.CharField(default='STANDARD', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_kg',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=8),
        ),
        migrations.AddField(
            model_name='product',
            name='width_cm',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
    ]
