# Generated by Django 5.2 on 2026-07-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_height_cm_product_length_cm_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['position', 'id'], 'verbose_name': 'Product Image', 'verbose_name_plural': 'Product Images'},
        ),
        migrations.AddField(
            model_name='productimage',
            name='position',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
    ]
