# Generated by Django 5.2 on 2026-01-15 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistics', '0001_initial'),
        ('products', '0001_initial'),
        ('sellers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('READY_FOR_DELIVERY', 'Ready for Delivery'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('shipping_address', models.TextField(help_text='Full delivery address')),
                ('delivery_zone', models.CharField(blank=True, help_text='e.g., Lusaka CBD, Kitwe Riverside, Ndola Town Center', max_length=100)),
                ('delivery_instructions', models.TextField(blank=True, help_text='Special delivery instructions (gate code, landmarks, etc.)')),
                ('delivered_at', models.DateTimeField(blank=True, help_text='Timestamp when order was delivered', null=True)),
                ('confirmed_by_buyer', models.BooleanField(default=False, help_text='Buyer has confirmed receiving the order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete timestamp (order never truly deleted for audit trail)', null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('delivery_partner', models.ForeignKey(blank=True, help_text='Assigned courier/rider for delivery', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='logistics.deliverypartner')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of units ordered')),
                ('price_snapshot', models.DecimalField(decimal_places=2, help_text='Price per unit at time of order (immutable)', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete timestamp (preserves order history)', null=True)),
                ('order', models.ForeignKey(help_text='Parent order containing this item', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(help_text='Product being purchased', on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.product')),
                ('seller', models.ForeignKey(help_text='Seller who owns this product (cached from product.seller)', on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='sellers.seller')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['order', 'seller'], name='orders_orde_order_i_5b910f_idx'), models.Index(fields=['product'], name='orders_orde_product_32ff41_idx')],
            },
        ),
    ]
