# Generated by Django 5.0.1 on 2026-06-04 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_is_superuser_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Primary phone number for SMS verification', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False, help_text='Phone number verified via SMS code'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, help_text='When phone was verified', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('BUYER', 'Buyer'), ('SELLER', 'Seller'), ('COURIER', 'Courier'), ('ADMIN', 'Admin')], db_index=True, default='BUYER', max_length=10),
        ),
        migrations.CreateModel(
            name='BuyerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Home', help_text='Address nickname (Home, Work, etc.)', max_length=50)),
                ('street_address', models.TextField(help_text='Street/building/plot number')),
                ('town_city', models.CharField(help_text='Town or city name', max_length=100)),
                ('province', models.CharField(help_text='Province name', max_length=100)),
                ('postal_code', models.CharField(blank=True, help_text='Optional postal code', max_length=20)),
                ('delivery_notes', models.TextField(blank=True, help_text='GPS coordinates, landmarks, gate instructions')),
                ('is_default', models.BooleanField(default=False, help_text='Use this address by default at checkout')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Buyer who owns this address', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Buyer Address',
                'verbose_name_plural': 'Buyer Addresses',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(choices=[('MOBILE_MONEY', 'Mobile Money'), ('CARD', 'Debit/Credit Card'), ('WALLET', 'Optimistic Wallet')], help_text='Type of payment method', max_length=20)),
                ('provider', models.CharField(choices=[('MTN_MOMO', 'MTN Mobile Money'), ('AIRTEL_MONEY', 'Airtel Money'), ('ZAMTEL', 'Zamtel Kwacha'), ('VISA', 'Visa'), ('MASTERCARD', 'Mastercard'), ('OPTIMISTIC', 'Optimistic Wallet')], help_text='Payment provider', max_length=20)),
                ('account_identifier', models.CharField(help_text='Encrypted phone number or card token', max_length=255)),
                ('account_name', models.CharField(help_text='Account holder name', max_length=100)),
                ('is_default', models.BooleanField(default=False, help_text='Use this payment method by default')),
                ('verified', models.BooleanField(default=False, help_text='Payment method verified (e.g., SMS code sent)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Buyer who owns this payment method', on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
