# Generated by Django 5.2 on 2026-03-13 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_initial'),
        ('accounts', '0004_user_phone_number_user_phone_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyeraddress',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Structured delivery location (province/city/zone)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_addresses', to='logistics.zambianlocation'),
        ),
    ]
