# Generated by Django 5.2 on 2026-07-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_email_verified_accountverificationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountverificationcode',
            name='purpose',
            field=models.CharField(choices=[('ACCOUNT_VERIFICATION', 'Account Verification'), ('PASSWORD_RESET', 'Password Reset')], db_index=True, default='ACCOUNT_VERIFICATION', max_length=30),
        ),
    ]
