# Generated by Django 5.2 on 2026-01-15 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(help_text='Public-facing store name', max_length=100)),
                ('phone', models.CharField(help_text='Contact number for delivery coordination', max_length=20)),
                ('profile_image', models.ImageField(blank=True, help_text='Store/seller profile picture', null=True, upload_to='sellers/profiles/')),
                ('banner_image', models.ImageField(blank=True, help_text='Store banner/cover image', null=True, upload_to='sellers/banners/')),
                ('description', models.TextField(blank=True, help_text='Store description and about information')),
                ('verified', models.BooleanField(default=False, help_text='Must be True to publish products. Set by admin only.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seller',
                'verbose_name_plural': 'Sellers',
            },
        ),
    ]
