# Generated by Django 5.2 on 2026-03-13 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='business_name',
            field=models.CharField(blank=True, help_text='Legal business name (if different from store name)', max_length=200),
        ),
        migrations.AddField(
            model_name='seller',
            name='business_registration_number',
            field=models.CharField(blank=True, help_text='PACRA or BDS registration number', max_length=100),
        ),
        migrations.AddField(
            model_name='seller',
            name='business_type',
            field=models.CharField(blank=True, choices=[('SOLE_TRADER', 'Sole Trader'), ('PARTNERSHIP', 'Partnership'), ('COMPANY', 'Registered Company')], help_text='Type of business entity', max_length=20),
        ),
        migrations.AddField(
            model_name='seller',
            name='payout_account_name',
            field=models.CharField(blank=True, help_text='Account holder name (must match ID)', max_length=200),
        ),
        migrations.AddField(
            model_name='seller',
            name='payout_account_number',
            field=models.CharField(blank=True, help_text='Account number or mobile money phone number', max_length=100),
        ),
        migrations.AddField(
            model_name='seller',
            name='payout_method',
            field=models.CharField(blank=True, choices=[('BANK', 'Bank Account'), ('MOBILE_MONEY', 'Mobile Money')], help_text='How seller receives payments', max_length=20),
        ),
        migrations.AddField(
            model_name='seller',
            name='payout_provider',
            field=models.CharField(blank=True, choices=[('MTN_MOMO', 'MTN Mobile Money'), ('AIRTEL_MONEY', 'Airtel Money'), ('ZAMTEL', 'Zamtel Kwacha'), ('BANK', 'Bank Transfer')], help_text='Payment provider', max_length=20),
        ),
        migrations.AddField(
            model_name='seller',
            name='physical_address',
            field=models.TextField(blank=True, help_text='Business street address, plot number'),
        ),
        migrations.AddField(
            model_name='seller',
            name='province',
            field=models.CharField(blank=True, help_text='Province', max_length=100),
        ),
        migrations.AddField(
            model_name='seller',
            name='tax_pin',
            field=models.CharField(blank=True, help_text='Tax Identification Number (TPIN)', max_length=50),
        ),
        migrations.AddField(
            model_name='seller',
            name='town_city',
            field=models.CharField(blank=True, help_text='Town or city', max_length=100),
        ),
        migrations.AddField(
            model_name='seller',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Admin notes on verification (visible to seller if rejected)'),
        ),
        migrations.AddField(
            model_name='seller',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending - Not Submitted'), ('SUBMITTED', 'Documents Submitted'), ('UNDER_REVIEW', 'Under Admin Review'), ('VERIFIED', 'Verified and Active'), ('REJECTED', 'Rejected - Resubmission Required')], default='PENDING', help_text='Current KYC verification status', max_length=20),
        ),
        migrations.AddField(
            model_name='seller',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When seller was verified', null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Admin who verified this seller', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_sellers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seller',
            name='verified',
            field=models.BooleanField(db_index=True, default=False, help_text='Must be True to publish products. Set by admin only.'),
        ),
        migrations.CreateModel(
            name='SellerVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('government_id_type', models.CharField(choices=[('NRC', 'National Registration Card'), ('PASSPORT', 'Passport'), ('DRIVERS_LICENSE', "Driver's License")], help_text='Type of government ID', max_length=20)),
                ('government_id_number', models.CharField(help_text='ID number (encrypted in production)', max_length=50)),
                ('government_id_front', models.ImageField(help_text='Front of ID card', upload_to='kyc/ids/')),
                ('government_id_back', models.ImageField(help_text='Back of ID card', upload_to='kyc/ids/')),
                ('selfie_with_id', models.ImageField(blank=True, help_text='Selfie holding ID (optional, for advanced fraud prevention)', null=True, upload_to='kyc/selfies/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, help_text='When documents were submitted')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When admin reviewed the documents', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Verification status', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (shown to seller)')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed this verification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_kyc', to=settings.AUTH_USER_MODEL)),
                ('seller', models.OneToOneField(help_text='Seller being verified', on_delete=django.db.models.deletion.CASCADE, related_name='kyc_documents', to='sellers.seller')),
            ],
            options={
                'verbose_name': 'Seller Verification Documents',
                'verbose_name_plural': 'Seller Verification Documents',
            },
        ),
    ]
