# Generated by Django 5.2 on 2026-03-13 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_initial'),
        ('sellers', '0002_seller_business_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='primary_location',
            field=models.ForeignKey(blank=True, help_text='Primary operating location (province/city/zone)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sellers', to='logistics.zambianlocation'),
        ),
    ]
