# Generated by Django 5.2 on 2026-07-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0003_seller_primary_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='payout_account_verified',
            field=models.BooleanField(default=False, help_text='Admin confirmed payout account ownership matches seller identity.'),
        ),
        migrations.AlterField(
            model_name='sellerverification',
            name='government_id_number',
            field=models.CharField(help_text='ID number (encrypted in production)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='sellerverification',
            name='selfie_with_id',
            field=models.ImageField(blank=True, help_text='Selfie holding ID required for seller identity matching', null=True, upload_to='kyc/selfies/'),
        ),
    ]
