import { useQuery } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import ProductCard from '../components/ProductCard';
import { api, list } from '../lib/api';

export default function Home() {
  const products = useQuery({ queryKey: ['products', 'home'], queryFn: () => api('/products/?ordering=-created_at') });
  const categories = useQuery({ queryKey: ['categories'], queryFn: () => api('/categories/') });
  const rows = list(products.data), categoryRows = list(categories.data);
  return <main className="portal-home">
    <section className="portal-search-zone"><div className="market-container"><nav className="market-modes" aria-label="Marketplace modes"><Link className="active" to="/products">Products</Link><Link to="/products">Sellers</Link><Link to="/rfqs">Request quotations</Link><Link to="/courier/register">Delivery partners</Link></nav><p className="portal-intro">Discover products from verified sellers across Zambia.</p></div></section>
    <section className="portal-welcome"><div className="market-container"><strong>Welcome to Optimistic</strong><nav><Link to="/rfqs">Request a quotation</Link><Link to="/products?ordering=-created_at">New arrivals</Link><Link to="/products?in_stock=true">Ready to deliver</Link></nav></div></section>
    <section className="market-container portal-discovery"><aside className="portal-categories"><div className="portal-panel-title"><strong>Categories for you</strong><Link to="/products">View all</Link></div>{categoryRows.slice(0, 7).map((category) => <Link to={`/products?category=${category.id}`} key={category.id}><span>{category.name.slice(0, 1)}</span>{category.name}<b>›</b></Link>)}</aside><div className="frequent-grid">{rows.slice(0, 3).map((product) => <Link className="frequent-card" to={`/products/${product.id}`} key={product.id}><small>Frequently searched</small><h2>{product.category_name}</h2><div>{product.images?.[0]?.image_url ? <img src={product.images[0].image_url} alt={product.name} /> : <span>{product.name.slice(0, 2)}</span>}</div><strong>{product.name}</strong></Link>)}</div><Link className="portal-promo" to="/register"><small>SELL DIRECT</small><h2>Grow your business with Optimistic</h2><p>Reach buyers across Zambia with verified commerce tools.</p><span>Start selling</span></Link></section>
    <section className="market-container portal-deals"><div className="portal-section-title"><div><h2>Top deals</h2><p>Strong value from marketplace sellers</p></div><Link to="/products?ordering=price">View more ›</Link></div><div className="deal-row">{rows.slice(3, 9).map((product) => <Link to={`/products/${product.id}`} key={product.id}><div>{product.images?.[0]?.image_url ? <img src={product.images[0].image_url} alt={product.name} /> : <span>{product.name.slice(0, 2)}</span>}</div><strong>K {Number(product.price).toLocaleString('en-ZM')}</strong><small>{product.available_stock} available</small></Link>)}</div></section>
    <section className="portal-recommendations"><div className="market-container"><div className="portal-section-title"><div><h2>Recommended for you</h2><p>Fresh products from verified sellers</p></div><Link to="/products">Explore catalog ›</Link></div>{products.isLoading && <p className="notice">Loading marketplace…</p>}{products.error && <p className="notice error">{products.error.message}</p>}<div className="recommendation-grid">{rows.slice(0, 18).map((product) => <ProductCard product={product} key={product.id} />)}</div></div></section>
  </main>;
}
