import { useState } from 'react';
import { useParams } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { api } from '../lib/api';
import { Screen, Status } from '../components/State';

export default function ProductEdit() {
  const { id } = useParams(); const queryClient = useQueryClient(); const [draft, setDraft] = useState(null); const [file, setFile] = useState(null); const [dragging, setDragging] = useState(null);
  const query = useQuery({ queryKey: ['seller-product', id], queryFn: async () => { const value = await api(`/products/${id}/`); setDraft(value); return value; } });
  const save = useMutation({ mutationFn: () => api(`/products/${id}/`, { method: 'PATCH', body: JSON.stringify({ name: draft.name, description: draft.description, price: draft.price, stock: Number(draft.stock), weight_kg: draft.weight_kg || null, length_cm: draft.length_cm || null, width_cm: draft.width_cm || null, height_cm: draft.height_cm || null, attributes: draft.attributes }) }), onSuccess: () => queryClient.invalidateQueries({ queryKey: ['seller-products'] }) });
  const upload = useMutation({ mutationFn: async () => { const body = new FormData(); body.append('image', file); return api(`/products/${id}/upload_image/`, { method: 'POST', body }); }, onSuccess: () => { setFile(null); query.refetch(); } });
  const remove = useMutation({ mutationFn: (imageId) => api(`/products/${id}/delete_image/?image_id=${imageId}`, { method: 'DELETE' }), onSuccess: () => query.refetch() });
  const primary = useMutation({ mutationFn: (imageId) => api(`/products/${id}/set_primary_image/`, { method: 'POST', body: JSON.stringify({ image_id: imageId }) }), onSuccess: () => query.refetch() });
  const reorder = useMutation({ mutationFn: (imageIds) => api(`/products/${id}/reorder_images/`, { method: 'POST', body: JSON.stringify({ image_ids: imageIds }) }), onSuccess: () => query.refetch() });
  const drop = (target) => { if (dragging === null || dragging === target) return; const ids = draft.images.map((image) => image.id); const from = ids.indexOf(dragging), to = ids.indexOf(target); ids.splice(to, 0, ids.splice(from, 1)[0]); setDraft({ ...draft, images: ids.map((imageId) => draft.images.find((image) => image.id === imageId)) }); setDragging(null); reorder.mutate(ids); };
  const change = (event) => setDraft({ ...draft, [event.target.name]: event.target.value });
  return <Screen eyebrow="SELLER CATALOG" title="Edit product" description="Update listing, inventory, shipping measurements and image selection."><Status loading={query.isLoading} error={query.error || save.error || upload.error || remove.error || primary.error || reorder.error} />{draft && <div className="seller-products"><form className="form card-panel" onSubmit={(event) => { event.preventDefault(); save.mutate(); }}>{['name', 'description', 'price', 'stock', 'weight_kg', 'length_cm', 'width_cm', 'height_cm'].map((key) => <label key={key}>{key.replaceAll('_', ' ')}<input name={key} type={['description', 'name'].includes(key) ? 'text' : 'number'} step="0.01" value={draft[key] ?? ''} onChange={change} /></label>)}<button disabled={save.isPending}>Save product</button></form><section className="card-panel"><h2>Images</h2><p>Drag images to reorder them.</p><div className="image-manager">{draft.images.map((image) => <article draggable onDragStart={() => setDragging(image.id)} onDragOver={(event) => event.preventDefault()} onDrop={() => drop(image.id)} key={image.id}><img src={image.image_url || image.image} alt="Product" /><span>{image.is_primary ? 'Primary' : `Position ${image.position + 1}`}</span><button className="button-quiet" onClick={() => primary.mutate(image.id)}>Set primary</button><button className="button-quiet" onClick={() => remove.mutate(image.id)}>Remove</button></article>)}</div><label>Add image<input type="file" accept="image/*" onChange={(event) => setFile(event.target.files[0])} /></label><button disabled={!file || upload.isPending} onClick={() => upload.mutate()}>Upload</button></section></div>}</Screen>;
}
