# Generated by Django 5.2 on 2026-01-15 22:03

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Confirmed earnings ready for payout', max_digits=12)),
                ('pending_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Earnings awaiting delivery confirmation', max_digits=12)),
                ('lifetime_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total earnings since registration', max_digits=12)),
                ('last_payout_at', models.DateTimeField(blank=True, help_text='Last successful payout timestamp', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Courier Wallet',
                'verbose_name_plural': 'Courier Wallets',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_address', models.TextField(help_text='Seller location')),
                ('delivery_address', models.TextField(help_text='Buyer location')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('ASSIGNED', 'Assigned'), ('PICKED_UP', 'Picked Up'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('partner_type', models.CharField(choices=[('RIDER', 'Motorcycle Rider'), ('COURIER', 'Courier Service'), ('BUS', 'Bus Station'), ('SELF', 'Seller Self-Delivery')], default='RIDER', max_length=10)),
                ('service_area', models.CharField(help_text='e.g., Lusaka CBD, Kabulonga, Chilenje', max_length=200)),
                ('verified', models.BooleanField(default=False, help_text='Admin verified this partner (ID, background check, etc.)')),
                ('is_active', models.BooleanField(default=True)),
                ('vehicle_type', models.CharField(blank=True, help_text='e.g., Motorcycle, Van, Bicycle', max_length=50)),
                ('id_number', models.CharField(blank=True, help_text='National ID or Driver License number', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Delivery Partner',
                'verbose_name_plural': 'Delivery Partners',
            },
        ),
        migrations.CreateModel(
            name='ZambianLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location_type', models.CharField(choices=[('PROVINCE', 'Province'), ('CITY', 'City'), ('ZONE', 'Zone/Area')], max_length=10)),
                ('delivery_base_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Base delivery cost for this location', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Zambian Location',
                'verbose_name_plural': 'Zambian Locations',
                'ordering': ['location_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CourierPayoutBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(help_text='Start date of earning period')),
                ('period_end', models.DateField(help_text='End date of earning period')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total payout amount for this batch', max_digits=12)),
                ('courier_count', models.PositiveIntegerField(default=0, help_text='Number of couriers in this batch')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('PAID', 'Paid Out'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payout_batches', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_payout_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Courier Payout Batch',
                'verbose_name_plural': 'Courier Payout Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourierEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Earning amount for this delivery', max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Confirmation'), ('CLEARED', 'Cleared for Payout'), ('PAID', 'Paid Out'), ('DISPUTED', 'Under Dispute'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payout_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earnings', to='logistics.courierpayoutbatch')),
            ],
            options={
                'verbose_name': 'Courier Earning',
                'verbose_name_plural': 'Courier Earnings',
                'ordering': ['-created_at'],
            },
        ),
    ]
