# Generated by Django 5.2 on 2026-01-15 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistics', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='orders.order'),
        ),
        migrations.AddField(
            model_name='courierearning',
            name='delivery',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='earning', to='logistics.delivery'),
        ),
        migrations.AddField(
            model_name='deliverypartner',
            name='user',
            field=models.OneToOneField(blank=True, help_text='User account for partner login (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_partner_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='delivery',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='logistics.deliverypartner'),
        ),
        migrations.AddField(
            model_name='courierwallet',
            name='courier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='logistics.deliverypartner'),
        ),
        migrations.AddField(
            model_name='courierearning',
            name='courier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='logistics.deliverypartner'),
        ),
        migrations.AddField(
            model_name='zambianlocation',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent location (Zone → City → Province)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='logistics.zambianlocation'),
        ),
        migrations.AddIndex(
            model_name='courierearning',
            index=models.Index(fields=['courier', 'status'], name='logistics_c_courier_a47534_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='zambianlocation',
            unique_together={('name', 'location_type', 'parent')},
        ),
    ]
