# Generated by Django 5.2 on 2026-07-10 21:57

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_alter_delivery_status_deliveryevent'),
        ('orders', '0005_orderitem_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_code', models.CharField(max_length=40)),
                ('shipping_class', models.CharField(default='STANDARD', max_length=30)),
                ('base_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('per_kg_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dimensional_divisor', models.DecimalField(decimal_places=2, default=Decimal('5000.00'), max_digits=8)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.DecimalField(decimal_places=3, max_digits=8)),
                ('dimensional_weight_kg', models.DecimalField(decimal_places=3, max_digits=8)),
                ('chargeable_weight_kg', models.DecimalField(decimal_places=3, max_digits=8)),
                ('length_cm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('width_cm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('height_cm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quoted_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('declared_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fulfillment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='orders.orderfulfillment')),
                ('shipping_rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='logistics.shippingrate')),
            ],
        ),
    ]
