# Generated by Django 5.2 on 2026-07-10 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_shippingrate_package'),
        ('orders', '0005_orderitem_cancellation_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustodyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('SELLER_RELEASED', 'Seller Released'), ('COURIER_RECEIVED', 'Courier Received'), ('BUS_OPERATOR_RECEIVED', 'Bus Operator Received'), ('DESTINATION_ARRIVED', 'Destination Arrived'), ('BUYER_RECEIVED', 'Buyer Received')], max_length=30)),
                ('external_reference', models.CharField(max_length=150, unique=True)),
                ('releasing_party', models.CharField(max_length=150)),
                ('receiving_party', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=200)),
                ('waybill_number', models.CharField(blank=True, max_length=100)),
                ('seal_identifier', models.CharField(blank=True, max_length=100)),
                ('verification_method', models.CharField(default='OTP', max_length=30)),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custody_events', to='logistics.package')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_custody_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COURIER_ASSIGNED', 'Courier Assigned'), ('PICKED_UP', 'Picked Up'), ('IN_TRANSIT', 'In Transit'), ('SELLER_RECEIVED', 'Seller Received'), ('CONDITION_VERIFIED', 'Condition Verified'), ('REFUND_AUTHORIZED', 'Refund Authorized'), ('CLOSED', 'Closed')], db_index=True, default='REQUESTED', max_length=24)),
                ('reason', models.TextField()),
                ('return_by', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='orders.order')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('condition', models.CharField(blank=True, choices=[('UNOPENED', 'Unopened'), ('RESALEABLE', 'Resaleable'), ('DAMAGED', 'Damaged'), ('MISSING', 'Missing')], max_length=15)),
                ('inspection_notes', models.TextField(blank=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_lines', to='orders.orderitem')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='logistics.returnrequest')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('return_request', 'order_item'), name='unique_return_request_line')],
            },
        ),
    ]
