# Generated by Django 5.2 on 2026-01-15 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('USER_SUSPEND', 'User Suspended'), ('USER_REINSTATE', 'User Reinstated'), ('USER_TERMINATE', 'User Terminated'), ('ESCROW_FREEZE', 'Escrow Frozen'), ('ESCROW_RELEASE', 'Escrow Released'), ('ESCROW_MANUAL_RELEASE', 'Manual Escrow Release'), ('DISPUTE_RESOLVE_BUYER', 'Dispute Resolved - Buyer Favor'), ('DISPUTE_RESOLVE_SELLER', 'Dispute Resolved - Seller Favor'), ('DISPUTE_RESOLVE_SPLIT', 'Dispute Resolved - Split Decision'), ('PRODUCT_APPROVE', 'Product Approved'), ('PRODUCT_FLAG', 'Product Flagged'), ('PRODUCT_REMOVE', 'Product Removed'), ('ORDER_OVERRIDE', 'Order Status Override'), ('ORDER_CANCEL_ADMIN', 'Order Cancelled by Admin'), ('SETTINGS_CHANGE', 'System Settings Changed'), ('RULE_CHANGE', 'Business Rule Changed')], help_text='What action was performed', max_length=50)),
                ('target_type', models.CharField(help_text='Model name of target (User, Order, Product, etc.)', max_length=50)),
                ('target_id', models.IntegerField(help_text='Primary key of target object')),
                ('details', models.JSONField(help_text='Additional context (reason, amounts, old/new values)')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of admin performing action')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When action was performed (UTC)')),
                ('actor', models.ForeignKey(help_text='Admin who performed this action', on_delete=django.db.models.deletion.PROTECT, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'permissions': [('view_audit_logs', 'Can view audit logs')],
                'indexes': [models.Index(fields=['actor', 'timestamp'], name='common_audi_actor_i_268ebf_idx'), models.Index(fields=['action', 'timestamp'], name='common_audi_action_6014bc_idx'), models.Index(fields=['target_type', 'target_id'], name='common_audi_target__65ba7e_idx')],
            },
        ),
    ]
