# Generated by Django 5.2 on 2026-04-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('USER_SUSPEND', 'User Suspended'), ('USER_REINSTATE', 'User Reinstated'), ('USER_TERMINATE', 'User Terminated'), ('ESCROW_FREEZE', 'Escrow Frozen'), ('ESCROW_RELEASE', 'Escrow Released'), ('ESCROW_MANUAL_RELEASE', 'Manual Escrow Release'), ('DISPUTE_RESOLVE_BUYER', 'Dispute Resolved - Buyer Favor'), ('DISPUTE_RESOLVE_SELLER', 'Dispute Resolved - Seller Favor'), ('DISPUTE_RESOLVE_SPLIT', 'Dispute Resolved - Split Decision'), ('PRODUCT_APPROVE', 'Product Approved'), ('PRODUCT_FLAG', 'Product Flagged'), ('PRODUCT_REMOVE', 'Product Removed'), ('ORDER_OVERRIDE', 'Order Status Override'), ('ORDER_CANCEL_ADMIN', 'Order Cancelled by Admin'), ('SETTINGS_CHANGE', 'System Settings Changed'), ('RULE_CHANGE', 'Business Rule Changed'), ('VERIFICATION_REQUEST', 'Verification Code Requested'), ('VERIFICATION_CONFIRM_SUCCESS', 'Verification Code Confirmed'), ('VERIFICATION_CONFIRM_FAILURE', 'Verification Code Failed'), ('VERIFICATION_LOCKOUT', 'Verification Lockout Triggered')], help_text='What action was performed', max_length=50),
        ),
    ]
