# Generated by Django 5.2 on 2026-01-15 22:03

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderFinancialSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Sum of all order items', max_digits=12)),
                ('commission_amount', models.DecimalField(decimal_places=2, help_text='Platform commission (calculated from rules)', max_digits=12)),
                ('seller_earnings', models.DecimalField(decimal_places=2, help_text='What seller receives (subtotal - commission)', max_digits=12)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Delivery cost (goes to courier)', max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Additional platform fees (processing, etc.)', max_digits=10)),
                ('status', models.CharField(choices=[('HELD', 'Held in Escrow'), ('RELEASED', 'Released to Seller'), ('REFUNDED', 'Refunded to Buyer'), ('PARTIAL_REFUND', 'Partially Refunded')], default='HELD', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Order Financial Snapshot',
                'verbose_name_plural': 'Order Financial Snapshots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Commission percentage (e.g., 10.00 for 10%)', max_digits=5)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now, help_text='When this rule becomes active')),
                ('is_active', models.BooleanField(default=True, help_text='Active rules are applied to new orders')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, help_text='Leave blank for default rule', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to='products.category')),
            ],
            options={
                'verbose_name': 'Commission Rule',
                'verbose_name_plural': 'Commission Rules',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='EscrowAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Confirmed earnings ready for payout', max_digits=12)),
                ('pending_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Earnings awaiting delivery confirmation', max_digits=12)),
                ('lifetime_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total earnings since account creation', max_digits=12)),
                ('last_payout_at', models.DateTimeField(blank=True, help_text='Last successful payout timestamp', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escrow_account', to='sellers.seller')),
            ],
            options={
                'verbose_name': 'Escrow Account',
                'verbose_name_plural': 'Escrow Accounts',
            },
        ),
    ]
