# Generated by Django 5.2 on 2026-01-15 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finances', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfinancialsnapshot',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='financial_snapshot', to='orders.order'),
        ),
        migrations.AddIndex(
            model_name='commissionrule',
            index=models.Index(fields=['category', 'is_active'], name='finances_co_categor_25694d_idx'),
        ),
    ]
