# Generated by Django 5.2 on 2026-07-10 21:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0001_initial'),
        ('finances', '0002_initial'),
        ('logistics', '0003_alter_delivery_status_deliveryevent'),
        ('orders', '0005_orderitem_cancellation_reason_and_more'),
        ('sellers', '0003_seller_primary_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscrowFreeze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='ZMW', max_length=3)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RELEASED', 'Released'), ('REFUNDED', 'Refunded')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('dispute', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='escrow_freeze', to='disputes.dispute')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escrow_freezes', to='orders.order')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='escrow_freezes', to='orders.orderitem')),
            ],
        ),
        migrations.CreateModel(
            name='LedgerTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=160, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=50)),
                ('currency', models.CharField(default='ZMW', max_length=3)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_transactions', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(db_index=True, max_length=80)),
                ('side', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=6)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='logistics.deliverypartner')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='sellers.seller')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='finances.ledgertransaction')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ledger_entry_positive_amount')],
            },
        ),
    ]
