# Generated by Django 5.2 on 2026-07-10 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_escrowfreeze_ledgertransaction_ledgerentry'),
        ('sellers', '0003_seller_primary_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerPayoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('provider', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('EXPORTED', 'Exported'), ('PAID', 'Paid'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('provider_reference', models.CharField(blank=True, max_length=150)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payout_requests', to='sellers.seller')),
            ],
        ),
    ]
