# Generated by Django 5.2 on 2026-01-15 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_object_id', models.PositiveIntegerField(help_text='ID of the disputed object')),
                ('reason', models.CharField(choices=[('ITEM_NOT_RECEIVED', 'Item Not Received'), ('ITEM_DAMAGED', 'Item Damaged in Transit'), ('WRONG_ITEM', 'Wrong Item Received'), ('DEFECTIVE_PRODUCT', 'Defective/Broken Product'), ('MISSING_PARTS', 'Missing Parts/Items'), ('NOT_AS_DESCRIBED', 'Not As Described'), ('SELLER_UNRESPONSIVE', 'Seller Not Responding'), ('DELIVERY_DELAY', 'Excessive Delivery Delay'), ('FRAUDULENT_REVIEW', 'Fraudulent/Fake Review'), ('OTHER', 'Other (See Description)')], max_length=30)),
                ('description', models.TextField(help_text='Detailed explanation of the issue')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('EVIDENCE', 'Collecting Evidence'), ('UNDER_REVIEW', 'Under Admin Review'), ('RESOLVED', 'Resolved'), ('ESCALATED', 'Escalated'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evidence_deadline', models.DateTimeField(blank=True, help_text='Deadline for submitting evidence', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_disputes', to=settings.AUTH_USER_MODEL)),
                ('target_content_type', models.ForeignKey(help_text='Type of object being disputed (Order, OrderItem, Delivery, Review)', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Dispute',
                'verbose_name_plural': 'Disputes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('PHOTO', 'Photo/Image'), ('DOCUMENT', 'Document/PDF'), ('TEXT', 'Text Note'), ('VIDEO', 'Video'), ('AUDIO', 'Audio Recording')], max_length=20)),
                ('file', models.FileField(blank=True, help_text='Evidence file (photo, document, etc.)', null=True, upload_to='disputes/evidence/')),
                ('note', models.TextField(blank=True, help_text='Text explanation or context')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='disputes.dispute')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dispute Evidence',
                'verbose_name_plural': 'Dispute Evidence',
                'ordering': ['submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('BUYER_FAVOR', 'Resolved in Buyer Favor'), ('SELLER_FAVOR', 'Resolved in Seller Favor'), ('PARTIAL_BUYER', 'Partial Resolution - Buyer'), ('PARTIAL_SELLER', 'Partial Resolution - Seller'), ('NO_FAULT', 'No Fault Found'), ('COURIER_FAULT', 'Courier at Fault')], max_length=20)),
                ('financial_action', models.CharField(choices=[('REFUND_FULL', 'Full Refund to Buyer'), ('REFUND_PARTIAL', 'Partial Refund to Buyer'), ('SELLER_PENALTY', 'Penalty to Seller'), ('COURIER_PENALTY', 'Penalty to Courier'), ('NONE', 'No Financial Action')], default='NONE', max_length=20)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount to refund (if applicable)', max_digits=10, null=True)),
                ('penalty_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Penalty amount (if applicable)', max_digits=10, null=True)),
                ('resolution_notes', models.TextField(help_text='Admin explanation of decision')),
                ('actions_completed', models.BooleanField(default=False, help_text='All financial/system actions executed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actions_completed_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resolved_disputes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dispute Resolution',
                'verbose_name_plural': 'Dispute Resolutions',
            },
        ),
        migrations.AddField(
            model_name='dispute',
            name='resolution',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispute_case', to='disputes.disputeresolution'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['status', 'created_at'], name='disputes_di_status_edf3a9_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['target_content_type', 'target_object_id'], name='disputes_di_target__9a96c8_idx'),
        ),
    ]
