# Generated by GitHub Copilot on 2026-04-27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('order', 'product', 'reviewer')},
        ),
    ]
