# Generated by Django 5.2 on 2026-01-15 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('ORDER', 'Order'), ('PRODUCT', 'Product'), ('DELIVERY', 'Delivery'), ('SELLER', 'Seller'), ('SYSTEM', 'System')], help_text='Category for filtering and icons', max_length=10)),
                ('title', models.CharField(help_text='Short headline (shown in list)', max_length=200)),
                ('message', models.TextField(help_text='Full notification text (shown in detail)')),
                ('is_read', models.BooleanField(default=False, help_text='User can mark as read via API')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_id', models.IntegerField(blank=True, help_text='ID of related object (order, product, delivery, etc.)', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
