# Generated by Django 5.2 on 2026-04-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False, help_text='User can mark as read via API'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ORDER', 'Order'), ('PRODUCT', 'Product'), ('DELIVERY', 'Delivery'), ('SELLER', 'Seller'), ('SYSTEM', 'System')], db_index=True, help_text='Category for filtering and icons', max_length=10),
        ),
    ]
